// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: arithmetic_svc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_arithmetic_svc_proto protoreflect.FileDescriptor

const file_arithmetic_svc_proto_rawDesc = "" +
	"\n" +
	"\x14arithmetic_svc.proto\x12\x02pb\x1a\x10number_msg.proto2\xf4\x01\n" +
	"\x11ArithmeticService\x124\n" +
	"\vGetAddition\x12\x17.pb.OperationParameters\x1a\n" +
	".pb.Answer\"\x00\x127\n" +
	"\x0eGetSubtraction\x12\x17.pb.OperationParameters\x1a\n" +
	".pb.Answer\"\x00\x12:\n" +
	"\x11GetMultiplication\x12\x17.pb.OperationParameters\x1a\n" +
	".pb.Answer\"\x00\x124\n" +
	"\vGetDivision\x12\x17.pb.OperationParameters\x1a\n" +
	".pb.Answer\"\x00B\x06Z\x04./pbb\x06proto3"

var file_arithmetic_svc_proto_goTypes = []any{
	(*OperationParameters)(nil), // 0: pb.OperationParameters
	(*Answer)(nil),              // 1: pb.Answer
}
var file_arithmetic_svc_proto_depIdxs = []int32{
	0, // 0: pb.ArithmeticService.GetAddition:input_type -> pb.OperationParameters
	0, // 1: pb.ArithmeticService.GetSubtraction:input_type -> pb.OperationParameters
	0, // 2: pb.ArithmeticService.GetMultiplication:input_type -> pb.OperationParameters
	0, // 3: pb.ArithmeticService.GetDivision:input_type -> pb.OperationParameters
	1, // 4: pb.ArithmeticService.GetAddition:output_type -> pb.Answer
	1, // 5: pb.ArithmeticService.GetSubtraction:output_type -> pb.Answer
	1, // 6: pb.ArithmeticService.GetMultiplication:output_type -> pb.Answer
	1, // 7: pb.ArithmeticService.GetDivision:output_type -> pb.Answer
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_arithmetic_svc_proto_init() }
func file_arithmetic_svc_proto_init() {
	if File_arithmetic_svc_proto != nil {
		return
	}
	file_number_msg_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arithmetic_svc_proto_rawDesc), len(file_arithmetic_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arithmetic_svc_proto_goTypes,
		DependencyIndexes: file_arithmetic_svc_proto_depIdxs,
	}.Build()
	File_arithmetic_svc_proto = out.File
	file_arithmetic_svc_proto_goTypes = nil
	file_arithmetic_svc_proto_depIdxs = nil
}
