// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: number_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_number_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_number_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_number_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Answer) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type OperationParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int32                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationParameters) Reset() {
	*x = OperationParameters{}
	mi := &file_number_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationParameters) ProtoMessage() {}

func (x *OperationParameters) ProtoReflect() protoreflect.Message {
	mi := &file_number_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationParameters.ProtoReflect.Descriptor instead.
func (*OperationParameters) Descriptor() ([]byte, []int) {
	return file_number_msg_proto_rawDescGZIP(), []int{1}
}

func (x *OperationParameters) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *OperationParameters) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

var File_number_msg_proto protoreflect.FileDescriptor

const file_number_msg_proto_rawDesc = "" +
	"\n" +
	"\x10number_msg.proto\x12\x02pb\"\x1e\n" +
	"\x06Answer\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\"1\n" +
	"\x13OperationParameters\x12\f\n" +
	"\x01a\x18\x01 \x01(\x05R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x05R\x01bB\x06Z\x04./pbb\x06proto3"

var (
	file_number_msg_proto_rawDescOnce sync.Once
	file_number_msg_proto_rawDescData []byte
)

func file_number_msg_proto_rawDescGZIP() []byte {
	file_number_msg_proto_rawDescOnce.Do(func() {
		file_number_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_number_msg_proto_rawDesc), len(file_number_msg_proto_rawDesc)))
	})
	return file_number_msg_proto_rawDescData
}

var file_number_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_number_msg_proto_goTypes = []any{
	(*Answer)(nil),              // 0: pb.Answer
	(*OperationParameters)(nil), // 1: pb.OperationParameters
}
var file_number_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_number_msg_proto_init() }
func file_number_msg_proto_init() {
	if File_number_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_number_msg_proto_rawDesc), len(file_number_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_number_msg_proto_goTypes,
		DependencyIndexes: file_number_msg_proto_depIdxs,
		MessageInfos:      file_number_msg_proto_msgTypes,
	}.Build()
	File_number_msg_proto = out.File
	file_number_msg_proto_goTypes = nil
	file_number_msg_proto_depIdxs = nil
}
